"""empty message

Revision ID: 4167267710a9
Revises: aabe91a3a421
Create Date: 2021-04-22 18:53:35.788480+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4167267710a9'
down_revision = 'aabe91a3a421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
